name: Bookpen's Blog
author: Chen hao
url: https://lightfish-zhang.github.io
resume_site: https://lightfish-zhang.github.io
baseurl: ""
description: you website desc
github_username: lightfish-zhang
github: https://github.com/bookpen
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : xxx
    clientSecret : xxx
    repo : lightfish-zhang.github.io
    owner : lightfish-zhang
    admin : lightfish-zhang
